### ISSUE TITLE
Missing icons in the field editor

### ISSUE THREAD

**Issue by mdlama** [anthonyfuentes/com_forms#2]
<img width="965" alt="Screen Shot 2019-04-06 at 1 42 46 PM" src="https://user-images.githubusercontent.com/4877315/55673154-e949fe00-5871-11e9-8b3a-e4c63356a0bb.png">

**Comment by anthonyfuentes** [comment]
I updated the code to work around a CSS class collision between the CMS and the form builder library. The icons should appear now.
